service: strava-activities-api

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'prod'}
  profile: iamadmin-general
  memorySize: 512
  timeout: 30

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
            - dynamodb:DescribeTable
          Resource:
            - "arn:aws:dynamodb:${self:provider.region}:*:table/strava-activities"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/strava-auth"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/strava-activities/index/*"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/strava-auth/index/*"

  environment:
    NODE_ENV: production
    DYNAMODB_ACTIVITIES_TABLE: strava-activities
    DYNAMODB_AUTH_TABLE: strava-auth
    STRAVA_CLIENT_ID: ${env:STRAVA_CLIENT_ID}
    STRAVA_CLIENT_SECRET: ${env:STRAVA_CLIENT_SECRET}
    STRAVA_REDIRECT_URI: ${env:STRAVA_REDIRECT_URI}
    FRONTEND_URL: ${env:FRONTEND_URL}
    GOOGLE_GEOCODING_API_KEY: ${env:GOOGLE_GEOCODING_API_KEY}

functions:
  api:
    handler: lambda.handler
    events:
      - http: # Changed from httpApi to http
          path: /{proxy+}
          method: ANY
          cors: true
      - http: # Changed from httpApi to http
          path: /
          method: ANY
          cors: true
    timeout: 30

  syncActivities:
    handler: sync-lambda.handler
    timeout: 900
    memorySize: 1024

plugins:
  - serverless-domain-manager
  - serverless-offline

custom:
  customDomain:
    domainName: strava-api.tri2dev.com
    basePath: ""
    stage: ${self:provider.stage}
    createRoute53Record: true
    certificateArn: "arn:aws:acm:us-east-1:451036201000:certificate/f0113d86-a59c-4fae-acaa-b45bf7f9e829"
    autoDomain: false
    endpointType: edge # Keep your existing EDGE configuration
  serverless-offline:
    httpPort: 3001

package:
  patterns:
    - "!node_modules/aws-sdk/**"
    - "!.git/**"
    - "!*.md"
    - "!test/**"
    - "!scripts/**"
